### ISSUE TITLE
panic: runtime error: nil pointer dereference in aws.flattenForwardedValues

### ISSUE THREAD

**Issue by cixtor** [cycloidio/terracognita#162]
**General information:**

| Question | Answer |
|-|-|
| Operating System | macOS |
| Terracognita version / tag | v0.6.0 |
| Did you build Terracognita from sources or did you use the Docker image | Downloaded an official release from here: https://github.com/cycloidio/terracognita/releases/tag/v0.6.0 |

**Describe the bug:**

panic: runtime error: invalid memory address or nil pointer dereference.

The operation always fails in this step: “Importing aws_cloudfront_distribution”.

After a quick search online, I found a commit in [Hashicorp/Terraform-provider-aws → 0139bf2](https://github.com/hashicorp/terraform-provider-aws/commit/0139bf217e0bb7b0dccbca95a62bdf26a4827c37) which apparently fixes the bug. However, the current (stable) version of Terracognita relies on an older version of this package (v1.60.1-0) from Aug 7th, 2020. A potential solution would be to upgrade to a newer version, but I did not test my assumptions. I want to leave it up to the maintainers to decide what the proper solution is.

**Log message**

```text
Starting Terracognita with version v0.6.0
Importing with filters:
  Tags:    [],
  Include: [],
  Exclude: [],
  Targets: [],
Importing aws_instance [23/23] Done!
Importing aws_alb [4/4] Done!
Importing aws_alb_listener [8/8] Done!
Importing aws_alb_listener_certificate [2/2] Done!
Importing aws_alb_listener_rule [9/9] Done!
Importing aws_alb_target_group [6/6] Done!
Importing aws_alb_target_group_attachment [8/8] Done!
Importing aws_cloudfront_distribution [7/7]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4a053cb]

goroutine 1 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.flattenForwardedValues(0x0, 0xc0014acd80)
github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/cloudfront_distribution_configuration_structure.go:430 +0x2b
github.com/terraform-providers/terraform-provider-aws/aws.flattenCloudFrontDefaultCacheBehavior(0xc0004a9600, 0xc51fda4)
github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/cloudfront_distribution_configuration_structure.go:268 +0x255
github.com/terraform-providers/terraform-provider-aws/aws.flattenDefaultCacheBehavior(...)
github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/cloudfront_distribution_configuration_structure.go:166
github.com/terraform-providers/terraform-provider-aws/aws.flattenDistributionConfig(0xc000446930, 0xc0008b2b40, 0xc00198f370, 0x0)
github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/cloudfront_distribution_configuration_structure.go:89 +0x14b
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsCloudFrontDistributionRead(0xc000446930, 0xb0ee040, 0xc00088c000, 0xc000446930, 0x0)
github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/resource_aws_cloudfront_distribution.go:729 +0x367
github.com/cycloidio/terracognita/provider.(*resource).refreshWithoutUpgrade(0xc00189b800, 0xc001b82960, 0xb0ee040, 0xc00088c000, 0x1, 0x177706f0, 0x8, 0x8)
github.com/cycloidio/terracognita/provider/resource.go:371 +0x225
github.com/cycloidio/terracognita/provider.(*resource).Read(0xc00189b800, 0xc0003ee9a0, 0xc0012d8000, 0x138e0050)
github.com/cycloidio/terracognita/provider/resource.go:236 +0x7a
github.com/cycloidio/terracognita/provider.Import.func1(0xc000482780, 0xc001b82960)
github.com/cycloidio/terracognita/provider/import.go:118 +0x3b
github.com/cycloidio/terracognita/util.Retry(0xc001b3fa08, 0x3, 0x6fc23ac00, 0x138e0050, 0x0)
github.com/cycloidio/terracognita/util/retry.go:23 +0x3c
github.com/cycloidio/terracognita/util.RetryDefault(...)
github.com/cycloidio/terracognita/util/retry.go:52
github.com/cycloidio/terracognita/provider.Import(0xd8b6fe0, 0xc0000560a8, 0xd9356e0, 0xc000538600, 0xd8b88a0, 0xc00101b5f0, 0xd8b88e0, 0xc00101b770, 0xc0003ee9a0, 0xd7a8fc0, ...)
github.com/cycloidio/terracognita/provider/import.go:118 +0xfe5
github.com/cycloidio/terracognita/cmd.glob..func2(0x1383e420, 0xc00029efc0, 0x0, 0xc, 0x0, 0x0)
github.com/cycloidio/terracognita/cmd/aws.go:104 +0x8db
github.com/spf13/cobra.(*Command).execute(0x1383e420, 0xc00029ef00, 0xc, 0xc, 0x1383e420, 0xc00029ef00)
github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x1383ec00, 0xc000000180, 0xc00041ff78, 0x10082e5)
github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
github.com/cycloidio/terracognita/main.go:11 +0x31
```

**Additional context**

N/A

**Comment by xescugc** [comment]
> After a quick search online, I found a commit in Hashicorp/Terraform-provider-aws → 0139bf2 which apparently fixes the bug. However, the current (stable) version of Terracognita relies on an older version of this package (v1.60.1-0) from Aug 7th, 2020. A potential solution would be to upgrade to a newer version, but I did not test my assumptions. I want to leave it up to the maintainers to decide what the proper solution is.

Hi @cixtor , yes upgrading would be the best solution but before I have to finish with https://github.com/cycloidio/terracognita/issues/151 which I'm working on but I found several issues on the way and I cannot give a time estimation right now but I'm working on it in parallel, once it's solved it'll already be updated to latest versions of the Providers :).
