### ISSUE TITLE
terracognita crash panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Ranchman42** [cycloidio/terracognita#182]
**General information:**

* Operating System:  Ubuntu 20.04, Amazon Linux 2
* Terracognita version / tag: v0.6.2, v0.6.0,  v0.6.3-3-g77825f8
* Did you build Terracognita from sources or did you use the Docker image:  Build from source and used the binary provided on github for linux

**Describe the bug:**

Everytime i try and run terracognita using this, or any other command in my environment i get a go lang crash stack trace

Strangely it did work the first time i ran terracognita but no matter what i do from changing OSes, to downgrading or compliling my own terracognita binary it won't work.

`
terracognita aws --module ec2 ~/us-west-2/ec2 --aws-default-region us-west-2
`

**Log message**
```
Starting Terracognita with version v0.6.2
Importing with filters:
        Tags:    [],
        Include: [],
        Exclude: [],
        Targets: [],
Importing aws_instance [3/3] Done!
Importing aws_alb [2/2] Done!
Importing aws_alb_listener [4/4] Done!
Importing aws_alb_listener_rule [4/4] Done!
Importing aws_alb_target_group [3/3] Done!
Importing aws_alb_target_group_attachment [3/3] Done!
Importing aws_api_gateway_deployment [3/3] Done!
Importing aws_api_gateway_stage [5/5] Done!
Importing aws_api_gateway_resource [6/6] Done!
Importing aws_api_gateway_rest_api [3/3] Done!
Importing aws_cloudfront_distribution [1/3]panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x3e07ccb]

goroutine 1 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.flattenForwardedValues(0x0, 0xc00181fcb0)
        /tmp/build/6b18b934/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/cloudfront_distribution_configuration_structure.go:430 +0x2b
github.com/terraform-providers/terraform-provider-aws/aws.flattenCloudFrontDefaultCacheBehavior(0xc0007adf80, 0xb91ef1b)
        /tmp/build/6b18b934/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/cloudfront_distribution_configuration_structure.go:268 +0x255
github.com/terraform-providers/terraform-provider-aws/aws.flattenDefaultCacheBehavior(...)
        /tmp/build/6b18b934/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/cloudfront_distribution_configuration_structure.go:166
github.com/terraform-providers/terraform-provider-aws/aws.flattenDistributionConfig(0xc001397340, 0xc000e863f0, 0xc0015b1c00, 0x0)
        /tmp/build/6b18b934/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/cloudfront_distribution_configuration_structure.go:89 +0x14b
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsCloudFrontDistributionRead(0xc001397340, 0xa4edc60, 0xc00095c500, 0xc001397340, 0x0)
        /tmp/build/6b18b934/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.1-0.20200807230610-d5346d47e3af/aws/resource_aws_cloudfront_distribution.go:729 +0x367
github.com/cycloidio/terracognita/provider.(*resource).refreshWithoutUpgrade(0xc0018afb00, 0xc0017545f0, 0xa4edc60, 0xc00095c500, 0x1, 0x7f223979b428, 0x8, 0x8)
        /tmp/build/6b18b934/code/provider/resource.go:373 +0x225
github.com/cycloidio/terracognita/provider.(*resource).Read(0xc0018afb00, 0xc0011fb500, 0xc00154f6c0, 0x12d04158)
        /tmp/build/6b18b934/code/provider/resource.go:238 +0x7a
github.com/cycloidio/terracognita/provider.Import.func1(0xc000116de0, 0xc0017545f0)
        /tmp/build/6b18b934/code/provider/import.go:118 +0x3b
github.com/cycloidio/terracognita/util.Retry(0xc001d07a10, 0x3, 0x6fc23ac00, 0x12d04158, 0x0)
        /tmp/build/6b18b934/code/util/retry.go:23 +0x3c
github.com/cycloidio/terracognita/util.RetryDefault(...)
        /tmp/build/6b18b934/code/util/retry.go:52
github.com/cycloidio/terracognita/provider.Import(0xccb55a0, 0xc000050088, 0xcd33a60, 0xc000712a80, 0xccb6e60, 0xc000712b00, 0x0, 0x0, 0xc0011fb500, 0xcba7a60, ...)
        /tmp/build/6b18b934/code/provider/import.go:118 +0xfe5
github.com/cycloidio/terracognita/cmd.glob..func2(0x12c620a0, 0xc00071ed70, 0x1, 0x5, 0x0, 0x0)
        /tmp/build/6b18b934/code/cmd/aws.go:112 +0x8af
github.com/spf13/cobra.(*Command).execute(0x12c620a0, 0xc00071ed20, 0x5, 0x5, 0x12c620a0, 0xc00071ed20)
        /tmp/build/6b18b934/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x12c62880, 0xc000084778, 0xc0003b7f78, 0x4062c5)
        /tmp/build/6b18b934/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /tmp/build/6b18b934/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /tmp/build/6b18b934/code/main.go:11 +0x31
```

**Additional context**

is happening every time i try to run terracognita on this infrastructure, it did work the first time i tried but every other time it has crashed just like this.

I have tried on Amazon Linux 2, Ubuntu 20.04, and with multiple versions of terracognita, even compiling my own binary from source.

**Comment by xescugc** [comment]
Hi @Ranchman42 !

I'll close this issue because it's repeated from https://github.com/cycloidio/terracognita/issues/162 and we already have that on the mind :).

The main issue "was" on AWS provider, they fixed it and we have to update to a newer version, we cannot do that as of now because some specific internals have to be updated beforehand. I'll retake this issue ASAP because it's blocking updates of the code base and we do not want that :)
